- name: using ansible modules
  hosts: localhost
  become: yes   # for root user
  tasks: 
  - name: installing nginix  # installing packages we use pakage module
    ansible.builtin.package:
      name: nginx
      state: present  # present to install absent to uninstall
  - name: installing nginix  # using  service module
    ansible.builtin.service:
      name:  nginx
      state: started      # started/stoped/restarted/reloded
      enabled: yes        # enabled yes/no 
  - name: createing user with name user
    ansible.builtin.user: # createing user by using user module
      name: user
      state: present  
  - name: using command module  
    ansible.builtin.command: ls /home/centos/ansible
      register: NAME
  - name: printing the given in variable NAME # using debug 
    ansible.builtin.debug:
      msg: "printing value of NAME IS: {{NAME}}"
  
  
  